services:
  DevSpace\Services\PrimesTable:
    class: DevSpace\Services\PrimesTable
    arguments: [ '@DevSpace\MathLib\IncrementalSieve' , '@DevSpace\MathLib\TimesTable' ]

  DevSpace\Services\TableConsoleOutput:
    class: DevSpace\Services\TableConsoleOutput
    arguments: [ '@Console_Table' ]


